this["JST"] = this["JST"] || {};

this["JST"]["client/templates/action.hbs"] = Handlebars.template({"compiler":[6,">= 2.0.0-beta.1"],"main":function(depth0,helpers,partials,data) {
  var helper, functionType="function", helperMissing=helpers.helperMissing, escapeExpression=this.escapeExpression;
  return "<div class=\"content container\">\n	<h2>SEE PERCOLATE IN ACTION</h2>\n	<div class=\"demo-form-container container\">\n		<section class=\"demo-form\">\n			<p>See how Percolate can help you grow revenue and deliver better customer experiences</p>\n			<form id=\"perc-form\" class=\"perc-form\">\n				<input type=\"text\" name=\"firstname\" placeholder=\"First Name\" value=\""
    + escapeExpression(((helper = (helper = helpers.firstname || (depth0 != null ? depth0.firstname : depth0)) != null ? helper : helperMissing),(typeof helper === functionType ? helper.call(depth0, {"name":"firstname","hash":{},"data":data}) : helper)))
    + "\">\n				<input type=\"text\" name=\"lastname\" placeholder=\"Last Name\" value=\""
    + escapeExpression(((helper = (helper = helpers.lastname || (depth0 != null ? depth0.lastname : depth0)) != null ? helper : helperMissing),(typeof helper === functionType ? helper.call(depth0, {"name":"lastname","hash":{},"data":data}) : helper)))
    + "\">\n				<input type=\"email\" name=\"email\" placeholder=\"Company Email\" value=\""
    + escapeExpression(((helper = (helper = helpers.email || (depth0 != null ? depth0.email : depth0)) != null ? helper : helperMissing),(typeof helper === functionType ? helper.call(depth0, {"name":"email","hash":{},"data":data}) : helper)))
    + "\">\n				<input type=\"text\" name=\"company\" placeholder=\"Company\" value=\""
    + escapeExpression(((helper = (helper = helpers.company || (depth0 != null ? depth0.company : depth0)) != null ? helper : helperMissing),(typeof helper === functionType ? helper.call(depth0, {"name":"company","hash":{},"data":data}) : helper)))
    + "\">\n				<input type=\"tel\" name=\"phone\" placeholder=\"Phone Number\" value=\""
    + escapeExpression(((helper = (helper = helpers.phone || (depth0 != null ? depth0.phone : depth0)) != null ? helper : helperMissing),(typeof helper === functionType ? helper.call(depth0, {"name":"phone","hash":{},"data":data}) : helper)))
    + "\">\n			</form>\n			<button class=\"perc-submit\"><strong>SEE PERCOLATE</strong></button>\n		</section>\n	</div>\n</div>\n\n";
},"useData":true});

this["JST"]["client/templates/casestudy.hbs"] = Handlebars.template({"compiler":[6,">= 2.0.0-beta.1"],"main":function(depth0,helpers,partials,data) {
  return "<hr>\n<h1>Results</h1>\n<div class=\"testimonial alternative\">\n	<div class=\"quote-body\">\n		<p>\n			\"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Id laboriosam ducimus libero quod repudiandae sit explicabo error. Debitis perferendis saepe consectetur, veniam asperiores quisquam. Obcaecati esse quam odit et fugit voluptatibus expedita laborum dicta architecto ipsum harum aspernatur necessitatibus, ex vel, repellendus inventore magnam qui fugiat reprehenderit non. Totam, explicabo.\"\n		</p>\n	</div>\n	<div class=\"quotee\">\n		<img src=\"\" alt=\"\">\n		<span>George Foreman -- Grilling Veteran</span>\n	</div>\n</div>\n\n<div class=\"case-study-section\">\n	<h3>Lorem Ipsum</h3>\n	<div class=\"copy\">\n		<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel atque provident distinctio explicabo eligendi reiciendis incidunt, quas omnis error! Fuga reprehenderit, quia nulla, quisquam alias facere doloremque maxime labore, expedita dolore laboriosam repellendus consequuntur sint suscipit! Sunt voluptates excepturi minima, voluptatibus officiis qui nihil quae tempore, autem officia distinctio explicabo.</p>\n	</div>\n	<img src=\"../images/valve-success-1.jpg\" alt=\"valve-1\">\n</div>\n\n<div class=\"case-study-section\">\n	<h3>Dolor Sit</h3>\n	<div class=\"copy\">\n		<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Molestias quaerat sed corporis error reiciendis repellat suscipit pariatur voluptatem! Nobis voluptas sit exercitationem, itaque qui et optio reprehenderit perferendis recusandae, voluptate dolores? Corrupti quisquam culpa molestiae expedita voluptate, quas molestias dolorem, aliquam, impedit eaque quae eos quia corporis? Vero, quo, ipsum.</p>\n	</div>\n	<img src=\"../images/valve-success-2.jpg\" alt=\"valve-1\">\n</div>\n\n<div class=\"case-study-section\">\n	<h3>Consectetur Adipisicing Elit</h3>\n	<div class=\"copy\">\n		<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Laudantium quia a praesentium nemo dolorem culpa, pariatur quae, adipisci omnis est sunt, obcaecati voluptate tempora consequuntur maiores quasi repellendus optio facilis. Non vel consequatur, perferendis sequi pariatur dolor voluptatem, repudiandae ea, quibusdam facilis, quisquam aperiam repellat! Ea provident eaque ad dolores.</p>\n	</div>\n	<img src=\"../images/valve-success-3.jpg\" alt=\"valve-1\">\n</div>\n\n<div class=\"case-study-section\">\n	<h3>Veniam Vero Quis</h3>\n	<div class=\"copy\">\n		<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Qui placeat cupiditate et rem vero natus praesentium dolorum vel odit quos, officia quaerat quae beatae sint veniam inventore repellat aliquam, veritatis nam expedita voluptates dolore provident ipsam! Nulla, nobis ipsam sapiente laudantium, possimus, quas culpa omnis, porro maxime itaque amet soluta.</p>\n	</div>\n	<img src=\"../images/valve-success-4.jpg\" alt=\"valve-1\">\n</div>\n\n";
  },"useData":true});

this["JST"]["client/templates/highlight.hbs"] = Handlebars.template({"compiler":[6,">= 2.0.0-beta.1"],"main":function(depth0,helpers,partials,data) {
  return "<section class=\"highlight\">\n	<div class=\"highlight copy\">\n		<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Velit hic numquam, a beatae voluptates eaque animi magnam ex, quo iure ut, saepe maxime quisquam quas obcaecati laudantium suscipit. Voluptatibus beatae explicabo, commodi molestias, officiis rerum, fuga numquam ea, modi dolorem blanditiis? Aliquam optio distinctio reprehenderit ipsa qui exercitationem quod laudantium.</p>\n	</div>\n</section>";
  },"useData":true});

this["JST"]["client/templates/navbar.hbs"] = Handlebars.template({"compiler":[6,">= 2.0.0-beta.1"],"main":function(depth0,helpers,partials,data) {
  return "<header id=\"navigation\" class=\"header container\">\n	<div class=\"logo\">\n		<a href=\"#!\">\n			<img src=\"http://percolate.com/static/images/logo.png\" alt=\"Percolate\">\n		</a>\n		<div class=\"nav-responsive\">\n			<div class=\"show-menu\"><i class=\"fa fa-bars fa-lg\"></i></div>\n		</div>\n	</div>\n	<div class=\"primary navigation\">\n		<ul>\n			<li><a href=\"#!\">Platform</a></li>\n			<li><a href=\"#!\">Services</a></li>\n			<li><a href=\"#!\">Clients</a></li>\n			<li><a href=\"#!\">Company</a></li>\n			<li><a href=\"#!\">Insights</a></li>\n			<li><a href=\"#!\">Blog</a></li>\n		</ul>\n	</div>\n	<div class=\"secondary navigation\">\n		<ul >\n			<li><a href=\"#!\">We're Hiring</a></li>\n			<li><a href=\"#!\">Login</a></li>\n			<li class=\"request-demo\"><a href=\"#!\">Request a Demo</a></li>\n		</ul>\n	</div>\n</header>";
  },"useData":true});

this["JST"]["client/templates/quote.hbs"] = Handlebars.template({"compiler":[6,">= 2.0.0-beta.1"],"main":function(depth0,helpers,partials,data) {
  return "<section class=\"quote\">\n	<p>\"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptatum natus asperiores veniam temporibus, corporis qui reiciendis magnam perferendis illo at obcaecati, dolore consequuntur ratione quidem.\"</p>\n	<div class=\"quotee\">\n		<img src=\"\" alt=\"\">\n		<span class=\"testimonial\">George Foreman -- Grilling Veteran</span>\n	</div>\n</section>";
  },"useData":true});

this["JST"]["client/templates/splash.hbs"] = Handlebars.template({"compiler":[6,">= 2.0.0-beta.1"],"main":function(depth0,helpers,partials,data) {
  return "<div class=\"splash-frame parallax-window\" data-parallax=\"scroll\" data-img-src=\"../images/valve-splash.jpg\">\n	<section class=\"splash-box\">\n		<div class=\"splash-content\">\n			<img src=\"../images/valve-logo.png\" alt=\"Valve\">\n			<h1>Lorem Ipsum Dolor Sit</h1>\n		</div>\n	</section>\n</div>";
  },"useData":true});